import { Layout, Input } from 'antd'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import useSWR from 'swr'

const fetcher = (url: string) => fetch(url).then((r) => r.json())

const { Header, Content } = Layout
const { Search } = Input

export default function Home() {
  const [search, setSearch] = useState<string>()
  const { data, error } = useSWR(
    'https://openlibrary.org/search.json?q=' + search,
    fetcher
  )

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Book Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout style={{ height: '100vh' }}>
        <Header>Logo</Header>
        <Content style={{ padding: '0 50px' }}>
          <Search placeholder="Search..." onSearch={setSearch} enterButton />

          {data.q}
        </Content>
      </Layout>
    </>
  )
}
