import BooksSearch from '@/components/BooksSearch'
import { Layout } from 'antd'
import Head from 'next/head'

const { Header, Content } = Layout

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout style={{ height: '100vh' }}>
        <Header>Logo</Header>
        <Content style={{ padding: '0 50px' }}>
          <BooksSearch />
        </Content>
      </Layout>
    </>
  )
}
